require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/artists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Artist. As you add validations to Artist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Artist.create! valid_attributes
      get artists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      artist = Artist.create! valid_attributes
      get artist_url(artist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_artist_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      artist = Artist.create! valid_attributes
      get edit_artist_url(artist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Artist" do
        expect {
          post artists_url, params: { artist: valid_attributes }
        }.to change(Artist, :count).by(1)
      end

      it "redirects to the created artist" do
        post artists_url, params: { artist: valid_attributes }
        expect(response).to redirect_to(artist_url(Artist.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Artist" do
        expect {
          post artists_url, params: { artist: invalid_attributes }
        }.to change(Artist, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post artists_url, params: { artist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested artist" do
        artist = Artist.create! valid_attributes
        patch artist_url(artist), params: { artist: new_attributes }
        artist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the artist" do
        artist = Artist.create! valid_attributes
        patch artist_url(artist), params: { artist: new_attributes }
        artist.reload
        expect(response).to redirect_to(artist_url(artist))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        artist = Artist.create! valid_attributes
        patch artist_url(artist), params: { artist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested artist" do
      artist = Artist.create! valid_attributes
      expect {
        delete artist_url(artist)
      }.to change(Artist, :count).by(-1)
    end

    it "redirects to the artists list" do
      artist = Artist.create! valid_attributes
      delete artist_url(artist)
      expect(response).to redirect_to(artists_url)
    end
  end
end
